### ISSUE TITLE
nvim laravel

### ISSUE THREAD

**Issue by ddiaz2380** [CodingWithLuis/.dotfiles#1]
Hola, vengo usando tu config de nvim desde que sigo tus videos, venia todo perfecto hasta el update de neovim y otras cositas, ya no me funciono mas el plugin de laravel y tampoco el treesiter con 2 o 3 cosas mas. Baje el update que hiciste en tu repo de nvim y sigue sin funcionar... alguna ayuda al respecto? Saludos!

**Comment by CodingWithLuis** [comment]
Hola, si lo que pasa es que algunos plugins cambiaron algunos cosas y se rompieron, si me puedes enviar imágenes o algo más para tener una mejor idea de donde está el problema.

**Comment by ddiaz2380** [comment]
NvimTreeToggle tampoco anda, al presionar leader nt ya no lo abre:
[https://www.dropbox.com/s/wno6t9hcx0nbr4d/01.png?dl=0](url)

Al precionar leader lp pasa esto no hace el preview y al ingresar a un archivo lo muestra vacio, como si no cargara el plugin:
[https://www.dropbox.com/s/qkp2re929kzcrkd/02.png?dl=0](url)
[https://www.dropbox.com/s/nqnfcturzqnb9ft/03.png?dl=0](url)

Al precionar leader la para que abra los comandos artisan, donde creo los modelos, controladores y demas da este error:
[https://www.dropbox.com/s/eo6n0rr5knh8p6v/04.png?dl=0](url)

Tampoco abre el hover de la instancia, no muestra el toggle explorer al lado del codigo para navegar como antes.
Cualquier otra cosa que me salga, lo reporte.
Gracias Saludos!

**Comment by CodingWithLuis** [comment]
Lo de NvimTree de momento lo quité porque estoy probando file browser en su lugar para navegar por los archivos, aún no estoy seguro si lo voy a instalar de nuevo por eso no te funciona.

Con respecto a lo de Laravel tuve que hacer unos cambios porque me estaba dando errores, pero no recuerdo que cambié, puedes hacer una de dos cosas o copias y pegas el código que tengo en el repositorio porque ese si me está funcionando o puedes instalar este paquete https://github.com/adalessa/laravel.nvim de ese autor copie y pegue para los plugin que ejecutas con la y con lp, luego él convirtió eso en un paquete.

Otra cosa es que los dotfiles actualmente funcionan con stow, para que te funcionen tienes que tener la misma estructura en tu pc, es decir, una carpeta .config/nvim y así con las demás en caso de que no tengas la misma estructura en tu sistema puedes solo copiar y pegar las cosas que te sirvan.

Otra cosa el LSPSaga que es el que tira el hover y demás está teniendo bastantes cambios en estos días y hay cosas de las de antes que ya no funcionan y se rompieron al menos en php (como el hover, find references, etc), todavía no lo he eliminado porque funciona bien en js, estoy buscando si encuentro un reemplazo con la misma funcionalidad, pero que soporte tanto php como js.

Cualquier cosa me avisas.

**Comment by ddiaz2380** [comment]
Ante todo, gracias luis por la atencion y tiempo, voy a probar lo que dices y veo si puedo solucionar algunas cosas y te comento. Gracias
